// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import {defineConfig, env} from "prisma/config";

export default defineConfig({
    schema: "prisma/schemas",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        // Runtime PrismaClient uses the PrismaPg adapter (connection.ts) and ignores this URL.
        // This URL is only used by Prisma CLI (migrate, studio) — use the session-mode pooler
        // which supports DDL statements, unlike the transaction-mode pooler (DATABASE_URL).
        url: env("DIRECT_URL"),
    },
});
